@startuml
GameWorld --> SpecialPropertiesContactResolver: resolve(fiziksEngine, contact, specialProperties)
alt specialProperties.isGlue
SpecialPropertiesContactResolver --> FiziksEngine: combine(bodyA, bodyB, position)
end
@enduml