@startuml
-> View: user taps power up button at index i
View -> GameInstanceController: activatePowerup(idx)
GameInstanceController -> EventManager: postEvent(PowerupButtonTappedEvent())
EventManager -> PowerupManager: send event to listener
PowerupManager -> Powerup: activate()
Powerup -> EventManager: postEvent(XXXPowerupActivatedEvent())
@enduml