@startuml
-> View: user taps power up button at index i
View -> GameInstanceController: activatePowerup(idx)
GameInstanceController -> GameEngine: activatePowerup(idx)
GameEngine -> GameWorld: activatePowerup(idx)
GameWorld -> PowerupManager: activatePowerup(idx)
PowerupManager -> Powerup: activate()
GameInstanceController -> ComponentB: activatePowerup(idx)
GameInstanceController -> ComponentC: activatePowerup(idx)
GameInstanceController -> ComponentD: activatePowerup(idx)
GameInstanceController -> ComponentE: activatePowerup(idx)
GameInstanceController -> ComponentF: activatePowerup(idx)
@enduml