@startuml
-> View: user taps powerup button at index i
View -> GameInstanceController: activatePowerup(idx)
GameInstanceController -> GameEngine: activatePowerup(idx)
GameEngine -> GameWorld: activatePowerup(idx)
GameWorld -> PowerupManager: activatePowerup(idx)
PowerupManager -> Powerup: activate()
@enduml