@startuml
create GameEngine

create GamePowerupManager
GameEngine -> GamePowerupManager: GamePowerupManager(seed)

[-> GameEngine: user receives powerup

GameEngine-> GamePowerupManager: createNextPowerup()

create GluePowerup
GamePowerupManager-> GluePowerup: GluePowerup.create()
@enduml