@startuml
create GameWorld

[-> GameWorld: user receives powerup

GameWorld-> GamePowerupManager: createNextPowerup()

GamePowerupManager -> GamePowerupManager: find empty slot in powerup array

alt if empty slot available at index i
create XXXPowerup
GamePowerupManager-> XXXPowerup: XXXPowerup.create()
GamePowerupManager -> GamePowerupManager: add powerup to empty slot
GamePowerupManager -> EventManager: postEvent(PowerupAvailableEvent(type, index, gameWorld))
end

EventManager -> GameInstanceController: send PowerupAvailableEvent
alt if correct gameWorld
GameInstanceController -> GameInstanceController: update own state
GameInstanceController -> View: show powerup button at index i
end
@enduml