@startuml activate powerup
[-> GameEngine: user receives powerup

GameEngine-> GamePowerupManager: createNextPowerup()

create EventManager

create GluePowerup

GamePowerupManager -> GluePowerup: GluePowerup.create()

GamePowerupManager -> EventManager: postEvent(GluePowerupActivatedEvent())

EventManager -> GamePowerupManager: PowerupButtonTappedEvent

GamePowerupManager -> GamePowerupManager: activateNextPowerup()

GamePowerupManager -> GluePowerup: activate()

GluePowerup -> GamePowerupManager: didActivateGluePowerup()

ref over GamePowerupManager, GameEngine: Executing logic to activate Glue powerup

@enduml