@startuml
create GameEngineManager
create GameUpdater


activate GameEngineManager

GameEngineManager -> GameUpdater: GameUpdater(runThisEveryFrame: update)
GameEngineManager -> GameUpdater: createCADisplayLink()

deactivate GameEngineManager


group Every Display Frame
GameUpdater -> GameEngineManager: update()

activate GameEngineManager

GameEngineManager -> GameEngine: update()
GameEngineManager -> GameEngineManager: renderCurrentFrame()

deactivate GameEngineManager

end

@enduml