@startuml
class GameEngine {
    - storageManager: StorageManager
    - eventManager: EventManager
    - gameWorld: GameWorld
    - achiementSystem: AchievementSystem
    - statsTrackingSystem: StatsTrackingSystem
    - gameMode: GameMode?
    + level: GameWorldLevel
    + init(levelDimensions: CGRect, eventManager: EventManager, playerId: UUID, storageManager: StorageManager)
    + startGame()
    + update()
    + stopGame()
    + pauseGame()
    + unpauseGame()
    + resetGame()
    + moveCMBSideways(by displacement: CGVector)
    + moveCMBDown(by displacement: CGVector)
    + rotateCMBClockwise()
    + rotateCMBCounterClockwise()
}

GameEngine --> GameWorld
GameEngine --> AchievementSystem
GameEngine --> StatsTrackingSystem
GameEngine --> GameMode
@enduml